2024-12-14T16:27:04,148 Using pip 24.3.1 from C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip (python 3.12)
2024-12-14T16:27:04,148 Non-user install because site-packages writeable
2024-12-14T16:27:05,791 Created temporary directory: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-build-tracker-noqpbn95
2024-12-14T16:27:05,791 Initialized build tracking at C:\Users\Rachit Nigam\AppData\Local\Temp\pip-build-tracker-noqpbn95
2024-12-14T16:27:05,791 Created build tracker: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-build-tracker-noqpbn95
2024-12-14T16:27:05,791 Entered build tracker: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-build-tracker-noqpbn95
2024-12-14T16:27:05,798 Created temporary directory: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-install-f5p85ydr
2024-12-14T16:27:06,233 Created temporary directory: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-ephem-wheel-cache-7sba9h06
2024-12-14T16:27:06,335 Requirement already satisfied: absl-py in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 10)) (2.1.0)
2024-12-14T16:27:06,335 Requirement already satisfied: aext-assistant in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 12)) (4.0.15)
2024-12-14T16:27:06,344 Requirement already satisfied: aext-assistant-server in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 14)) (4.0.15)
2024-12-14T16:27:06,344 Requirement already satisfied: aext-core in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 16)) (4.0.15)
2024-12-14T16:27:06,346 Requirement already satisfied: aext-core-server in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 18)) (4.0.15)
2024-12-14T16:27:06,350 Requirement already satisfied: aext-panels in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 20)) (4.0.15)
2024-12-14T16:27:06,354 Requirement already satisfied: aext-panels-server in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 22)) (4.0.15)
2024-12-14T16:27:06,358 Requirement already satisfied: aext-share-notebook in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 24)) (4.0.15)
2024-12-14T16:27:06,361 Requirement already satisfied: aext-share-notebook-server in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 26)) (4.0.15)
2024-12-14T16:27:06,361 Requirement already satisfied: aext-shared in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 28)) (4.0.15)
2024-12-14T16:27:06,365 Requirement already satisfied: aiobotocore in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 30)) (2.12.3)
2024-12-14T16:27:06,370 Requirement already satisfied: aiohappyeyeballs in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 32)) (2.4.0)
2024-12-14T16:27:06,373 Requirement already satisfied: aiohttp in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 34)) (3.10.5)
2024-12-14T16:27:06,375 Requirement already satisfied: aioitertools in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 36)) (0.7.1)
2024-12-14T16:27:06,376 Requirement already satisfied: aiosignal in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 38)) (1.2.0)
2024-12-14T16:27:06,376 Requirement already satisfied: alabaster in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 40)) (0.7.16)
2024-12-14T16:27:06,380 Requirement already satisfied: altair in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 42)) (5.0.1)
2024-12-14T16:27:06,385 Requirement already satisfied: anaconda-anon-usage in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 44)) (0.4.4)
2024-12-14T16:27:06,390 Requirement already satisfied: anaconda-catalogs in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 46)) (0.2.0)
2024-12-14T16:27:06,395 Requirement already satisfied: anaconda-client in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 48)) (1.12.3)
2024-12-14T16:27:06,397 Requirement already satisfied: anaconda-cloud-auth in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 50)) (0.5.1)
2024-12-14T16:27:06,399 Requirement already satisfied: anaconda-navigator in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 52)) (2.6.3)
2024-12-14T16:27:06,404 Requirement already satisfied: anaconda-project in c:\users\rachit nigam\anaconda3\lib\site-packages (from -r requirements.txt (line 54)) (0.11.1)
2024-12-14T16:27:06,406 1 location(s) to search for versions of anaconda-toolbox:
2024-12-14T16:27:06,406 * https://pypi.org/simple/anaconda-toolbox/
2024-12-14T16:27:06,450 Fetching project page and analyzing links: https://pypi.org/simple/anaconda-toolbox/
2024-12-14T16:27:06,484 Getting page https://pypi.org/simple/anaconda-toolbox/
2024-12-14T16:27:06,484 Found index url https://pypi.org/simple/
2024-12-14T16:27:06,796 Fetched page https://pypi.org/simple/anaconda-toolbox/ as application/vnd.pypi.simple.v1+json
2024-12-14T16:27:06,796   Found link https://files.pythonhosted.org/packages/32/6d/701303794552836ca49563492d09c9d1505ad7299888342fe2b80a051a4e/anaconda_toolbox-0.0.1-py2.py3-none-any.whl (from https://pypi.org/simple/anaconda-toolbox/), version: 0.0.1
2024-12-14T16:27:06,796   Found link https://files.pythonhosted.org/packages/3d/b7/08997579afe5916105db4bb4b88021ba926244f5391d504174ebc3febce3/anaconda_toolbox-0.0.1.tar.gz (from https://pypi.org/simple/anaconda-toolbox/), version: 0.0.1
2024-12-14T16:27:06,796 Skipping link: not a file: https://pypi.org/simple/anaconda-toolbox/
2024-12-14T16:27:06,796 Given no hashes to check 2 links for project 'anaconda-toolbox': discarding no candidates
2024-12-14T16:27:06,812 Collecting anaconda-toolbox (from -r requirements.txt (line 56))
2024-12-14T16:27:06,813   Obtaining dependency information for anaconda-toolbox from https://files.pythonhosted.org/packages/32/6d/701303794552836ca49563492d09c9d1505ad7299888342fe2b80a051a4e/anaconda_toolbox-0.0.1-py2.py3-none-any.whl.metadata
2024-12-14T16:27:06,813   Created temporary directory: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-unpack-98smf7gv
2024-12-14T16:27:06,813   Using cached anaconda_toolbox-0.0.1-py2.py3-none-any.whl.metadata (272 bytes)
2024-12-14T16:27:06,823   Created temporary directory: C:\Users\Rachit Nigam\AppData\Local\Temp\pip-metadata-3z44wuob
2024-12-14T16:27:06,833 1 location(s) to search for versions of anaconda-powershell-prompt:
2024-12-14T16:27:06,833 * https://pypi.org/simple/anaconda-powershell-prompt/
2024-12-14T16:27:06,835 Fetching project page and analyzing links: https://pypi.org/simple/anaconda-powershell-prompt/
2024-12-14T16:27:06,835 Getting page https://pypi.org/simple/anaconda-powershell-prompt/
2024-12-14T16:27:06,836 Found index url https://pypi.org/simple/
2024-12-14T16:27:07,265 Could not fetch URL https://pypi.org/simple/anaconda-powershell-prompt/: 404 Client Error: Not Found for url: https://pypi.org/simple/anaconda-powershell-prompt/ - skipping
2024-12-14T16:27:07,265 Skipping link: not a file: https://pypi.org/simple/anaconda-powershell-prompt/
2024-12-14T16:27:07,265 Given no hashes to check 0 links for project 'anaconda-powershell-prompt': discarding no candidates
2024-12-14T16:27:07,265 ERROR: Could not find a version that satisfies the requirement anaconda_powershell_prompt (from versions: none)
2024-12-14T16:27:07,785 Remote version of pip: 24.3.1
2024-12-14T16:27:07,785 Local version of pip:  24.3.1
2024-12-14T16:27:07,798 Was pip installed by pip? True
2024-12-14T16:27:07,798 ERROR: No matching distribution found for anaconda_powershell_prompt
2024-12-14T16:27:07,798 Exception information:
2024-12-14T16:27:07,798 Traceback (most recent call last):
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
2024-12-14T16:27:07,798     self._add_to_criteria(self.state.criteria, r, parent=None)
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 174, in _add_to_criteria
2024-12-14T16:27:07,798     raise RequirementsConflicted(criterion)
2024-12-14T16:27:07,798 pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('anaconda_powershell_prompt')
2024-12-14T16:27:07,798 
2024-12-14T16:27:07,798 During handling of the above exception, another exception occurred:
2024-12-14T16:27:07,798 
2024-12-14T16:27:07,798 Traceback (most recent call last):
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
2024-12-14T16:27:07,798     result = self._result = resolver.resolve(
2024-12-14T16:27:07,798                             ^^^^^^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
2024-12-14T16:27:07,798     state = resolution.resolve(requirements, max_rounds=max_rounds)
2024-12-14T16:27:07,798             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 399, in resolve
2024-12-14T16:27:07,798     raise ResolutionImpossible(e.criterion.information)
2024-12-14T16:27:07,798 pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('anaconda_powershell_prompt'), parent=None)]
2024-12-14T16:27:07,798 
2024-12-14T16:27:07,798 The above exception was the direct cause of the following exception:
2024-12-14T16:27:07,798 
2024-12-14T16:27:07,798 Traceback (most recent call last):
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
2024-12-14T16:27:07,798     status = _inner_run()
2024-12-14T16:27:07,798              ^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
2024-12-14T16:27:07,798     return self.run(options, args)
2024-12-14T16:27:07,798            ^^^^^^^^^^^^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
2024-12-14T16:27:07,798     return func(self, options, args)
2024-12-14T16:27:07,798            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
2024-12-14T16:27:07,798     requirement_set = resolver.resolve(
2024-12-14T16:27:07,798                       ^^^^^^^^^^^^^^^^^
2024-12-14T16:27:07,798   File "C:\Users\Rachit Nigam\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 104, in resolve
2024-12-14T16:27:07,798     raise error from e
2024-12-14T16:27:07,798 pip._internal.exceptions.DistributionNotFound: No matching distribution found for anaconda_powershell_prompt
2024-12-14T16:27:07,865 Removed build tracker: 'C:\\Users\\Rachit Nigam\\AppData\\Local\\Temp\\pip-build-tracker-noqpbn95'
